[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]

remappings = [
  "forge-std/=lib/forge-std/src/"
]

solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
deny_warnings = true

# Gas report (optional but recommended)
gas_reports = ["*"]

[rpc_endpoints]
anvil = "${ANVIL_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 256

[invariant]
runs = 64
depth = 32
fail_on_revert = false
